# Generated by Django 4.2.7 on 2023-11-11 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tamaño', models.CharField(blank=True, max_length=100, null=True)),
                ('encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_de_mantenimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('teléfono_encargado', models.CharField(blank=True, max_length=100, null=True)),
                ('descripción', models.TextField(blank=True, max_length=500, null=True)),
                ('ubicación', models.CharField(blank=True, max_length=100, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_de_área', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_de_ocupación', models.CharField(blank=True, max_length=100, null=True)),
                ('equipamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(default=datetime.date.today)),
                ('intervalo_mantenimiento', models.IntegerField(default=30)),
            ],
        ),
    ]
